// <auto-generated />
using System;
using Login.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Login.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Login.Models.AlumniGroup", b =>
                {
                    b.Property<int>("G_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("G_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("G_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("G_id")
                        .HasName("PK__alumni_group__3213E83F46A0C516");

                    b.ToTable("alumni_group", (string)null);
                });

            modelBuilder.Entity("Login.Models.UserGroup", b =>
                {
                    b.Property<int>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupId"));

                    b.Property<int?>("AlumniGroupG_id")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("G_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("UserTblId")
                        .HasColumnType("int");

                    b.HasKey("UserGroupId")
                        .HasName("PK__user_group__3213E83F46A0C516");

                    b.HasIndex("AlumniGroupG_id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserTblId");

                    b.ToTable("user_group", (string)null);
                });

            modelBuilder.Entity("Login.Models.UserTbl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("batch_number");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<string>("LinkedInId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("linkedin_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("RollNum")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("roll_num");

                    b.Property<int?>("YearOfGraduation")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("year_of_graduation");

                    b.HasKey("Id")
                        .HasName("PK__user_tbl__3213E83F46A0C516");

                    b.HasIndex(new[] { "Email" }, "UQ__user_tbl__AB6E6164EB168A93")
                        .IsUnique();

                    b.ToTable("user_tbl", (string)null);
                });

            modelBuilder.Entity("Login.Models.UserGroup", b =>
                {
                    b.HasOne("Login.Models.AlumniGroup", null)
                        .WithMany("UserGroups")
                        .HasForeignKey("AlumniGroupG_id");

                    b.HasOne("Login.Models.AlumniGroup", "AlumniGroup")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Login.Models.UserTbl", "UserTbl")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Login.Models.UserTbl", null)
                        .WithMany("UserGroups")
                        .HasForeignKey("UserTblId");

                    b.Navigation("AlumniGroup");

                    b.Navigation("UserTbl");
                });

            modelBuilder.Entity("Login.Models.AlumniGroup", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Login.Models.UserTbl", b =>
                {
                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
